### ISSUE TITLE
Ubercharge flashing between color selected in hud editor and purple

### ISSUE THREAD

**Issue by Silexos** [CriticalFlaw/flawhud#160]
Hi again I don't know how to show this off via a screenshot but upon building a full uber as medic, the center bar will flash between whatever selected color as well as this solid purple.

![20210601005532_1](https://user-images.githubusercontent.com/85089160/120289321-0756f180-c276-11eb-88bc-8138230ffe64.jpg)

**Comment by CriticalFlaw** [comment]
Oh this is an easy change from a mistake I made in the previous commit. Basically you want to go into `flawhud/scripts/hudanimations_custom.txt` go to line 91 and change the called color from UberChargeShadow to UberChargePulse. Do that on your side first and see if that fixes the issue. If it does, feel free to open a PR or I'll commit the change later today. Cheers

**Comment by CriticalFlaw** [comment]
Here's the direct line: https://github.com/CriticalFlaw/flawhud/blob/master/scripts/hudanimations_custom.txt#L91

**Comment by CriticalFlaw** [comment]
Fixed here https://github.com/CriticalFlaw/flawhud/commit/f9c367ca83f98f3255c30b9e411a38ff5ca10178#diff-cdb7d61a2cce1861fc9fe5d88e865a11201bd36dfa364df3f46d3b81ce9760ce. Please verify.

**Comment by Silexos** [comment]
Yep it's currently working! Apologies for the late response I was away today, but thanks again!

**Comment by Silexos** [comment]
Hiya sorry to reopen this but I noticed now that shadow of overheal/low health value will now mimic the color value rather than the typical black shadow of normal health values (note: the shadow of regular health values were not affected and still show their usual black)

![20210602130637_1](https://user-images.githubusercontent.com/85089160/120545431-7c741500-c3a3-11eb-8ee5-1a5c8505202b.jpg)

**Comment by CriticalFlaw** [comment]
That's an intentional change. I've changed it in the default flawhud to use a darkened color shadow instead of pure black for colored text.

**Comment by Silexos** [comment]
Oh alright! I'll just close the issue then, apologies. Maybe a black shadow option as an alternative could work in the future as a means to improve clarity when using brighter colors (as shown with the Aqua option from the editor).
