### ISSUE TITLE
Black "bar" under named/skin weapons

### ISSUE THREAD

**Issue by Dragonissa** [CriticalFlaw/flawhud#357]
Been happening in a couple of custom huds, sadly on this one as well.

Version: v2023.0730
Screen resolution: 2560x1600 (16:10)

~~This hud might have fixed it, havent tested yet.~~ Nope, also broken.
https://github.com/Hypnootize/hypnotizehud/commit/3f9d56df518923ba87e5e0c77415441e3671693f

There also seems to be this fix on the workshop, though without the files
https://steamcommunity.com/sharedfiles/filedetails/?id=3008891469

https://steamcommunity.com/groups/toonhud/discussions/0/3808407695167881266/

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/8d288fa4-6bd0-49c3-a616-85da793a4601)

**Comment by CriticalFlaw** [comment]
This was somewhat fixed a year ago here: https://github.com/CriticalFlaw/flawhud/issues/238

The fix was shared with budhud and hypnotize HUD, but specifically in tournament spectator where it's more noticeable.

I don't recall if there was a reason why the backpack screen still had the bar, might have to do with the resolution. I'll take a quick look when I can. Thanks.

**Comment by CriticalFlaw** [comment]
just did a quick check and it looks to not be an issue on 1080p and 1440p resolutions. At least with the weapon skin I had on hand. Could this be because the item name is one line or maybe it's only on your specific resolution?

![20230730160020_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/13c03d3a-6722-4276-803c-da3a0f683e30)

![20230730160033_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/6e3a1317-a17e-47f1-8943-dcdbc906ec47)

**Comment by Dragonissa** [comment]
![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/0078da26-cb39-43c4-9c3f-dc965ea85bc7)

Possible the resolution?


Edit:

Changed the resolution to 1920x1200 and now its gone. According to that the workshop fix its for resolutions of 4k, so it might start being an issue above xxxx X 1440?


![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/c7d1e008-4d39-47f6-a741-369f4a37244b)

Edit:

Based on the fix in hypnotizehud, i assume its due the weapon image being a specific height, but not the "socket" it sits in. This might be fine for 16:9 but not for 16:10.

**Comment by CriticalFlaw** [comment]
Possibly fixed in: 0e1a39f2e16715cc270b5aa91200c4ed7458345e

Please download the latest version and retest to confirm.

**Comment by Dragonissa** [comment]
What version is the TF2Hud Editor pulling? It doesn't seem to be the latest one as your changes aren't in there.

Edit: After manually adding the changes, it did something?

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/3882515f-dac9-44c4-b50a-bd1ab5e3f093)
![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/144f7110-88d2-49f5-b5d0-81e6aae6f68a)

**Comment by CriticalFlaw** [comment]
Latest schema version is supposed to pull directly from the master branch. Probably need to reinstall the HUD after the schema change.

Can't tell, did it fix the issue?

**Comment by Dragonissa** [comment]
I've reinstalled (reinstall, uninstall, install and apply) multiple times, that sadly didn't change much. It mentioned once that there was a schema update after starting it but even that didn't change the files for some reason.

It appeared to do something, the black bar is gone which is nice, though the weapon icon still appears to be squashed together.

**Comment by Dragonissa** [comment]
Just downloaded the repo itself, now the backpack is broken and the black bars are back.
![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/f8532279-2c6b-4f9e-b649-44fd843a39b7)

**Comment by CriticalFlaw** [comment]
Reverted the change that broke the backpack screen. Should be fine now.

**Comment by CriticalFlaw** [comment]
I sacrificed a name tag to reproduce the issue in the 2560x1600 resolution and it did not show up. I'm honestly content with closing this as a won't do and hope Valve eventually fixes this for all resolutions (or implement the workshop mod).

![20230802215616_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/44330e3a-2fcb-4b25-a1c5-ab1a84d26d0d)

**Comment by Dragonissa** [comment]
The image is only 2560x1440 though. I doubt it can be replicated by just using that resolution without the screen actually being 16:10.

Maybe i can find a hud without the issue and see whats different.

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/b45daab4-0a86-4b66-b1b2-5c36f62cea65)

Lined up

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/5eabe39e-040d-45eb-9161-6750871c1414)

**Comment by Dragonissa** [comment]
ToonHud is fine.

ToonHUD 11.4 (12/28/2022)
 - MvM: Added CurrencyStatusPanel back, that went missing after a recent TF2 update
- Fixed War Painted items showing black bars in loadout's item selection page on some screen resolutions

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/38aea512-04d2-44da-918b-c6f0cb2ad6e3)


I was able to fix it with the default loadout layout by copying over parts of the "classloadoutpanel.res", specifically "modelpanels_kv". This doesn't completely work since the other layout has different sizes, but at least the black bar is gone. Would still require some tinkering with the mentioned part and the layout sizes to make the icons no squashed.

Im sure at this point that its basically an issue with aspect ratio of the generated images, hence why its fine when the itempanel is this exact length and width ToonHud uses, but not if its any shorter or thinner.

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/6d7d0c10-f966-4ef8-9837-50a8567524c9)


This below is a straight copy of the whole "class_loadout_panel" block in the file.

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/e52ab560-f20d-4b52-bec3-aab63cdc8879)

```
"class_loadout_panel"
	{
		"ControlName"	"Frame"
		"fieldName"		"class_loadout_panel"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"settitlebarvisible"	"0"
		"PaintBackgroundType"	"0"
		"bgcolor_override"	"G_MenuBg"
		"infocus_bgcolor_override" "G_MenuBg"
		"outoffocus_bgcolor_override" "G_MenuBg"
		
		"item_xpos_offcenter_a"	"-340"
		"item_xpos_offcenter_b"	"190"
		"item_ypos"		"58"
		"item_ydelta"	"67"
		"item_mod_wide"	"40"
		
		"item_backpack_offcenter_x"		"-288"
		"item_backpack_xdelta"			"4"
		"item_backpack_ydelta"			"3"

		"button_xpos_offcenter"	"175"			
		"button_ypos"	"85"
		"button_ydelta"	"80"
		"button_override_delete_xpos" "0"
		
		"modelpanels_kv"
		{
			"ControlName"	"CItemModelPanel"
			"xpos"			"c-70"
			"ypos"			"270"
			"wide"			"150"
			"tall"			"64"
			"visible"		"0"
			"noitem_textcolor"		"117 107 94 255"
			"PaintBackgroundType"	"0"
			"paintbackground"	"1"
			"bgcolor_override" "G_LoadoutItemBg"
			"paintborder"	"1"

			"model_center_x"	"1"
			"model_ypos"		"4"
			"model_tall"		"40"
			"model_wide"		"69"
			"text_ypos"			"47"
			"text_center"		"1"
			"name_only"			"1"
			
			"attriblabel"
			{
				"font"			"ItemFontAttribLarge"
				"visible"		"0"
			}
			
			"itemmodelpanel"
			{
				"use_item_rendertarget" "0"
				"allow_rot"				"0"
				"inventory_image_type"	"0" // HQ images
			}
		}
		
		"itemoptionpanels_kv"
		{
			"ControlName"	"CExButton"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"12"
			"tall"			"12"
			"autoResize"	"0"
			"visible"		"0"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"+"
			"font"			"Default"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"defaultBgColor_override" "0 0 0 0"
		}
	}
```

**Comment by Dragonissa** [comment]
Even though its fixed, it probably will never work with the sizes you had before. Feel free to use it as a fix for 16:10 and the default loadout layout.

The wrench icon is still there, i accidentally overwrote while making the GIF.

```
		"class_loadout_panel"
	{
		"ControlName"	"Frame"
		"fieldName"		"class_loadout_panel"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"settitlebarvisible"	"0"
		"PaintBackgroundType"	"0"
		"bgcolor_override"	"DarkGrey"
		"infocus_bgcolor_override" "DarkGrey"
		"outoffocus_bgcolor_override" "DarkGrey"
		
		"item_xpos_offcenter_a"	"-340"
		"item_xpos_offcenter_b"	"190"
		"item_ypos"		"58"
		"item_ydelta"	"67"
		"item_mod_wide"	"40"
		
		"item_backpack_offcenter_x"		"-288"
		"item_backpack_xdelta"			"4"
		"item_backpack_ydelta"			"3"

		"button_xpos_offcenter"	"175"			
		"button_ypos"	"85"
		"button_ydelta"	"80"
		"button_override_delete_xpos" "0"
		
		"modelpanels_kv"
		{
			"ControlName"	"CItemModelPanel"
			"xpos"			"c-70"
			"ypos"			"270"
			"wide"			"150"
			"tall"			"64"
			"visible"		"0"
			"noitem_textcolor"		"117 107 94 255"
			"PaintBackgroundType"	"0"
			"paintbackground"	"1"
			"bgcolor_override" "Transparent"
			"paintborder"	"1"

			"model_center_x"	"1"
			"model_ypos"		"4"
			"model_tall"		"40"
			"model_wide"		"69"
			"text_ypos"			"47"
			"text_center"		"1"
			"name_only"			"1"
			
			"attriblabel"
			{
				"font"			"ItemFontAttribLarge"
				"visible"		"0"
			}
			
			"itemmodelpanel"
			{
				"use_item_rendertarget" "0"
				"allow_rot"				"0"
				"inventory_image_type"	"0" // HQ images
			}
		}
		
		"itemoptionpanels_kv"
		{
			"ControlName"	"CExButton"
			"xpos"	"0"
			"ypos"	"0"
			"zpos"	"1"
			"wide"	"20"
			"tall"	"20"
			"autoResize"	"0"
			"visible"	"0"
			"enabled"	"1"
			"tabPosition"	"0"
			"labelText"	"w"
			"font"	"SmallIcons"
			"textAlignment"	"center"
			"dulltext"	"0"
			"brighttext"	"0"
			"default"	"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"paintbackground"	"0"
			"defaultFgColor_override"	"TanLight"
			"armedFgColor_override"	"TanDark"
			"depressedFgColor_override"	"TanLight"
		}
	}
```

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/b7419983-96a8-4b59-bbd3-4798808c7ebe)


![Untitled](https://github.com/CriticalFlaw/flawhud/assets/4233773/caf85731-b376-499a-8ebc-301e29ca2cd8)

**Comment by Dragonissa** [comment]
I've also noticed that the item selection was broken as well


```
"ItemSelectionPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"ItemSelectionPanel"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"500"
		"wide"			"f0"
		"tall"			"400"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"settitlebarvisible"	"0"
		"bgcolor_override"		"DarkGrey"

		"item_ypos"					"60"
		"item_ydelta"				"80"
		"item_backpack_offcenter_x"	"-288"
		"item_backpack_xdelta"		"4"
		"item_backpack_ydelta"		"3"

		"modelpanels_selection_kv"
		{
			"wide"					"94"
			"tall"					"70"
			"model_ypos"			"5"
			"model_wide"			"75"
			"model_tall"			"50"
			"model_center_x"		"1"
			"text_ypos"				"0"
			"text_forcesize"		"2"
			"text_center"			"0"
			"text_yoffset"			"2"
			"name_only"				"1"
			"inset_eq_y"			"56"
			"inset_eq_x"			"56"
			
			"deferred_description"	"1"
			"deferred_icon"			"1"
		}

		"modelpanels_kv"
		{
			"ControlName"	"CItemModelPanel"
			"xpos"			"c-70"
			"ypos"			"270"
			"wide"			"54"
			"tall"			"42"
			"visible"		"0"
			"paintbackground"		"1"
			"bgcolor_override"		"Transparent"
			"noitem_textcolor"		"117 107 94 255"
			"PaintBackgroundType"	"2"
			"paintborder"	"1"
			
			"model_xpos"	"2"
			"model_ypos"	"5" 
			"model_wide"	"50"
			"model_tall"	"35"
			"text_ypos"		"60"
			"text_center"	"1"
			"name_only"		"1"
			
			"inset_eq_x"	"4"
			"inset_eq_y"	"2"
			"deferred_description"	"1"
			
			"itemmodelpanel"
			{
				"use_item_rendertarget" "0"
				"inventory_image_type"	"0" // HQ images
				"allow_rot"				"0"
			}
			
			"use_item_sounds"	"1"
		}

		"duplicatelabels_kv"
		{
			"font"			"FontRegular8"
			"textAlignment"	"center"
			"wide"			"20"
			"tall"			"15"
			"zpos"			"1"
			"autoResize"	"0"
			"pinCorner"		"0"
			"enabled"		"1"
			"fgcolor"		"153 204 255 255"
		}
	}
```
![Untitled2](https://github.com/CriticalFlaw/flawhud/assets/4233773/b460988c-5609-4765-b40a-7ef91243b0df)

**Comment by CriticalFlaw** [comment]
Submit a PR with your changes so it can be merged in since you've already done the work.

**Comment by Dragonissa** [comment]
Im not entirely sure how that affects 16:9 so i got to test that. 

I also want to recheck something, maybe i can get yours to work.

**Comment by CriticalFlaw** [comment]
I already reverted change. Once you have time to test and think it's good then please submit a PR.

**Comment by Dragonissa** [comment]
As expected, spectator icons are also broken. Most likely those 3 as well

* resource/ui/freezepanel_basic.res
* resource/ui/hudinspectpanel.res
* resource/ui/spectator.res
* 
![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/728e0b6e-ec6f-45cc-8c90-f945a0107ada)

**Comment by CriticalFlaw** [comment]
> As expected, spectator icons are also broken. Most likely those 3 as well
> 
> * resource/ui/freezepanel_basic.res
> * resource/ui/hudinspectpanel.res
> * resource/ui/spectator.res
> 
> ![image](https://user-images.githubusercontent.com/4233773/258242953-728e0b6e-ec6f-45cc-8c90-f945a0107ada.png)

freezepanel_basic, spectator and spectator_tournament use the same hudinspectpanel.res file for that panel so you only need to change it in one spot. Be sure to test this in all resolutions as this was fixed for 16:9 1440p.

**Comment by Dragonissa** [comment]
Alright. For that it seems as it was a simple line change. Ill try to find time to test it for the other resolutions.

```
                "model_ypos"			"20"
		"model_center_y"		"1"
		"model_center_x"		"1"
		"model_wide"			"75" <-- instead 80
		"model_tall"			"50"
		"noitem_use_fullpanel"	"0"
```

**Comment by CriticalFlaw** [comment]
Closing as resolved as there have not been any further reports of this happening since last release with the current changes.
